# Generated by Django 2.0.6 on 2018-07-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motherscnotes', '0002_characters_elder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='chap_num',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='characters',
            name='elder',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='characters',
            name='image',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='characters',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='characters',
            name='relatives',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='characters',
            name='village',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='diet',
            name='indigenous',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='fauna',
            name='classification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fauna',
            name='image',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='fauna',
            name='indigenous',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='fauna',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='flora',
            name='classification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='flora',
            name='image',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='flora',
            name='indigenous',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='flora',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nature',
            name='indigenous',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='nature',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supernatural',
            name='image',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='supernatural',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='image',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='tech',
            name='indigenous',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='tech',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
